<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>QuickOcr_Setup</AssemblyName>
    <RootNamespace>QuickOcr.Sfx</RootNamespace>
    <Version>1.0.0</Version>
    <Company>QuickOcr</Company>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="publish.zip" />
  </ItemGroup>

</Project>
